### ISSUE TITLE
No problems, just a question

### ISSUE THREAD

**Issue by Heya24** [Dabomstew/universal-pokemon-randomizer#113]
In PKMN White/Black and White 2/Black2, will Magneton still evolve into Magnezone when it gets to level 40 or is that only in PKMN Heartgold/Soulsilver?

**Comment by yopox** [comment]
You could generate a log file of the randomization to check 😉

**Comment by Dabomstew** [comment]
The log file won't mention Magnezone, since the original evolution method is fine for B/W and B2/W2 and does not require trading. Just utilise said original method (leveling in Chargestone Cave, which should easily be accessible by the time you could practically have a Lv40 Pokemon without overgrinding)
