### ISSUE TITLE
Rotom considered a legendary?

### ISSUE THREAD

**Issue by JkHowling** [Dabomstew/universal-pokemon-randomizer#46]
Another unrelated thing I noticed, though I doubt it's a bug, is that the randomizer considers Rotom a legendary for some reason? I selected for all in-game legends to be replaced with another legend, and the randomization log says everything worked.. except Reshiram is now a Rotom. 

This is actually very disappointing to me. I wanted it to be another legendary, to make things just as hard, if not harder- but a Rotom will add no difficulty at all. Furthermore, as it's a Black randomization, I'll be at the disadvantage- the Reshiram I could've caught? Now a less-than-stellar mon that won't match up at all to whatever replaces the Zekrom.

 I know it's been debated before, but it's been essentially confirmed at this point that Rotom is NOT a legendary. It shouldn't be considered in legendary => legendary randomization.

**Comment by Dabomstew** [comment]
Can confirm that this was intentional at the time it was decided. 

I'm not sure what justification I used since it has been so long, but Rotom's dex position (right at the start of the legendaries, or just before them depending on your perspective) may have been a factor. It may also have been a product of wanting to make sure that the TV Rotom was replaced with something "special" when this option was selected.

If/when there's another release, changing it may well be on the cards.

**Comment by JkHowling** [comment]
I figured it was a purposeful decision and decided some time ago, was just a bit confused and disappointed. I've never really had it happen til recently. Either of those explanations makes sense to me- it is a bit of a special mon pre-gen 6. Just a bit odd to see it late-game in the place of some frightening legend. Thanks again for the response.
